### ISSUE TITLE
Bug: Unit Test for MacOS has failed

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-Int-SB3#4]
**1 Describe the bug**

**2 To Reproduce**

**3 Expected behavior**

**4 Screenshots**

**5 Additional Informations**
![image](https://github.com/fhswf/MLPro-Int-SB3/assets/88610818/938ed681-91aa-46f5-843e-332aa940378f)
![image](https://github.com/fhswf/MLPro-Int-SB3/assets/88610818/f2bbfe69-07db-472f-a749-b236ef359147)

5.1 Operating System
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
We opted for variant 2
