### ISSUE TITLE
Bug: Gap between MLPro and SB3 Wrapper

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-Int-SB3#9]
**1 Describe the bug**
I have found a gap between MLPro and SB3, which also affects all the related howtos. I am using howto_rl_wp_002_validation_wrapped_sb3_on_policy.py as the testing file and obtained the following results:

1. MLPro v1.1.0, SB3 v1.7.0
![Screenshot 2024-06-11 102336](https://github.com/fhswf/MLPro-Int-SB3/assets/88610818/a116a826-e458-4ce6-bbc6-b01e95a87e3c)

2. MLPro v1.2.0, SB3 v2.1.0
![Screenshot 2024-06-11 100738](https://github.com/fhswf/MLPro-Int-SB3/assets/88610818/71e46dcd-56f9-4ffc-b701-f56b5ff75ac5)

3. MLPro v1.3.0, SB3 v2.1.0
![Screenshot 2024-06-11 100917](https://github.com/fhswf/MLPro-Int-SB3/assets/88610818/a93cb0c2-2bba-4f5b-aa9b-a5c13b33b612)

4. MLPro v1.4.4, SB3 v2.3.2
![Screenshot 2024-06-11 102909](https://github.com/fhswf/MLPro-Int-SB3/assets/88610818/1ccf72cd-efec-44ad-b90d-4e098f049f13)

It seems there are different outputs between SB3 v1.x.x to SB3 v2.x.x. This could be caused by the introduction of gymnasium instead of gym which affects the behaviour of the environment or the change of SB3 behaviour itself. I have checked the seeding is the same, but in the logging the states are different. So most likely, the first reason is the cause.

However, apart from the different outputs from the native SB3, our wrapper also produces different results from version 1.2.0 onwards. This is something I need to analyse further and find a solution.

The other potential cause is our gymnasium wrapper, which leads to incorrect behaviour that was not found in our previous gym wrapper.

**2 To Reproduce**
1. Go to howto_rl_wp_002_validation_wrapped_sb3_on_policy.py
2. Run the simulation

**3 Expected behavior**
Gap between 

**4 Screenshots**
See Point 1.

**5 Additional Informations**

5.1 Operating System
   - [ ] Linux
   - [x] Windows
   - [ ] Mac OS

**Comment by steveyuwono** [comment]
Hi @detlefarend , just fyi, our sb3 wrapper has not performed correctly since the introduction of gymnasium. The details are in the description above.

**Comment by steveyuwono** [comment]
Hi @detlefarend , after extensive and horrible debugging of three packages since yesterday, I have found and fixed the issue with the on-policy algorithm. The problem came from differences in behaviour between the integration of the SB3 policy and the gym environment using the native SB3 learning method without MLPro. First, the seeding was inconsistent. Previously, we had separate seeds for the gym environment and SB3. Now, they both use the same seed. There was nothing wrong with our SB3 wrapper, but there was an issue with the seeding in our gymnasium wrapper. Our predefined seed no longer affected the environment reset due to a different mechanism in gymnasium compared to gym. I have fixed this in MLPro-Int-Gymnasium. This could be the reason why our "howto_rl_att_001_train_and_reload_single_agent_gym_sd.py" script was no longer working as before.

Meanwhile, there is a bug with the off-policy algorithm originating from SB3 when running the SB3 policy with the gym environment natively (without MLPro). As shown in the attached screenshot, the next states and the done flag are sometimes incorrectly labelled, e.g. valid states as "terminate" and invalid states as not "terminate." I am pretty sure that our SB3 wrapper for off-policy behaves the same as the SB3 package. However, the validation how-to is incorrect due to a misinterpretation between SB3 and gymnasium. Therefore, I do not think it is worth spending more time trying to solve the howto.
![Screenshot 2024-06-12 113357](https://github.com/fhswf/MLPro-Int-SB3/assets/88610818/ff24b452-44d4-4441-85f9-9faa3a3f3569)

The next tasks to resolve this issue are:
1. Test "howto_rl_att_001_train_and_reload_single_agent_gym_sd.py".
2. Fix the unittest failures with MacOS in MLPro-Int-Gymnasium.
3. Release the new versions of MLPro-Int-Gymnasium and MLPro-Int-SB3.

**Comment by detlefarend** [comment]
> Hi @detlefarend , after extensive and horrible debugging of three packages since yesterday, I have found and fixed the issue with the on-policy algorithm. The problem came from differences in behaviour between the integration of the SB3 policy and the gym environment using the native SB3 learning method without MLPro. First, the seeding was inconsistent. Previously, we had separate seeds for the gym environment and SB3. Now, they both use the same seed. There was nothing wrong with our SB3 wrapper, but there was an issue with the seeding in our gymnasium wrapper. Our predefined seed no longer affected the environment reset due to a different mechanism in gymnasium compared to gym. I have fixed this in MLPro-Int-Gymnasium. This could be the reason why our "howto_rl_att_001_train_and_reload_single_agent_gym_sd.py" script was no longer working as before.
> 
> Meanwhile, there is a bug with the off-policy algorithm originating from SB3 when running the SB3 policy with the gym environment natively (without MLPro). As shown in the attached screenshot, the next states and the done flag are sometimes incorrectly labelled, e.g. valid states as "terminate" and invalid states as not "terminate." I am pretty sure that our SB3 wrapper for off-policy behaves the same as the SB3 package. However, the validation how-to is incorrect due to a misinterpretation between SB3 and gymnasium. Therefore, I do not think it is worth spending more time trying to solve the howto. ![Screenshot 2024-06-12 113357](https://private-user-images.githubusercontent.com/88610818/338917402-ff24b452-44d4-4441-85f9-9faa3a3f3569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTI4MjMsIm5iZiI6MTcxODE5MjUyMywicGF0aCI6Ii84ODYxMDgxOC8zMzg5MTc0MDItZmYyNGI0NTItNDRkNC00NDQxLTg1ZjktOWZhYTNhM2YzNTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDExNDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0N2NlN2E4MjBlYmFjZjgyMjVjOTAzZGFlYTNjNjZiZmMzNGUyYmQ4OWNhZGY3MWRjNTI4OWRiMDYwNDIyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aXQ_dC3cMe0XJQQCo2FdBXf8hI_s_444tywCLk3UxQ)
> 
> The next tasks to resolve this issue are:
> 
>     1. Test "howto_rl_att_001_train_and_reload_single_agent_gym_sd.py".
> 
>     2. Fix the unittest failures with MacOS in MLPro-Int-Gymnasium.
> 
>     3. Release the new versions of MLPro-Int-Gymnasium and MLPro-Int-SB3.

Hi @steveyuwono, that really sounds like hardcore debugging. Awesome, that you were able to locate the problems and clean the MLPro part. Regarding the remaining sb3 problem:  what do you think of reporting the problem by creating an issue in their repo with a small sample code?

**Comment by steveyuwono** [comment]
> > Hi @detlefarend , after extensive and horrible debugging of three packages since yesterday, I have found and fixed the issue with the on-policy algorithm. The problem came from differences in behaviour between the integration of the SB3 policy and the gym environment using the native SB3 learning method without MLPro. First, the seeding was inconsistent. Previously, we had separate seeds for the gym environment and SB3. Now, they both use the same seed. There was nothing wrong with our SB3 wrapper, but there was an issue with the seeding in our gymnasium wrapper. Our predefined seed no longer affected the environment reset due to a different mechanism in gymnasium compared to gym. I have fixed this in MLPro-Int-Gymnasium. This could be the reason why our "howto_rl_att_001_train_and_reload_single_agent_gym_sd.py" script was no longer working as before.
> > Meanwhile, there is a bug with the off-policy algorithm originating from SB3 when running the SB3 policy with the gym environment natively (without MLPro). As shown in the attached screenshot, the next states and the done flag are sometimes incorrectly labelled, e.g. valid states as "terminate" and invalid states as not "terminate." I am pretty sure that our SB3 wrapper for off-policy behaves the same as the SB3 package. However, the validation how-to is incorrect due to a misinterpretation between SB3 and gymnasium. Therefore, I do not think it is worth spending more time trying to solve the howto. ![Screenshot 2024-06-12 113357](https://private-user-images.githubusercontent.com/88610818/338917402-ff24b452-44d4-4441-85f9-9faa3a3f3569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTI4MjMsIm5iZiI6MTcxODE5MjUyMywicGF0aCI6Ii84ODYxMDgxOC8zMzg5MTc0MDItZmYyNGI0NTItNDRkNC00NDQxLTg1ZjktOWZhYTNhM2YzNTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDExNDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0N2NlN2E4MjBlYmFjZjgyMjVjOTAzZGFlYTNjNjZiZmMzNGUyYmQ4OWNhZGY3MWRjNTI4OWRiMDYwNDIyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aXQ_dC3cMe0XJQQCo2FdBXf8hI_s_444tywCLk3UxQ)
> > The next tasks to resolve this issue are:
> > ```
> > 1. Test "howto_rl_att_001_train_and_reload_single_agent_gym_sd.py".
> > 
> > 2. Fix the unittest failures with MacOS in MLPro-Int-Gymnasium.
> > 
> > 3. Release the new versions of MLPro-Int-Gymnasium and MLPro-Int-SB3.
> > ```
> 
> Hi @steveyuwono, that really sounds like hardcore debugging. Awesome, that you were able to locate the problems and clean the MLPro part. Regarding the remaining sb3 problem: what do you think of reporting the problem by creating an issue in their repo with a small sample code?

Sure, I can later prepare a small sample and report it there.
